//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpScanTests {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FakeMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FakeMessages() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharpScanTests.FakeMessages", typeof(FakeMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {&quot;jsonrpc&quot;:&quot;2.0&quot;,&quot;method&quot;:&quot;announce&quot;,&quot;params&quot;:{&quot;apiVersion&quot;:&quot;1.0&quot;,
        ///&quot;device&quot;:{&quot;familyType&quot;:&quot;QuantumX&quot;,&quot;firmwareVersion&quot;:&quot;4.1.1.18610.1&quot;,&quot;hardwareId&quot;:&quot;MX410_R0&quot;,
        ///&quot;name&quot;:&quot;MX410 Matthias&quot;,&quot;type&quot;:&quot;MX410&quot;,&quot;uuid&quot;:&quot;0009E500123A&quot;},&quot;expiration&quot;:15,
        ///&quot;netSettings&quot;:{&quot;defaultGateway&quot;:{&quot;ipv4Address&quot;:&quot;172.19.169.254&quot;},
        ///&quot;interface&quot;:{&quot;configurationMethod&quot;:&quot;dhcp&quot;,&quot;description&quot;:&quot;ethernet backplane side&quot;,
        ///&quot;ipv4&quot;:[{&quot;address&quot;:&quot;172.19.192.57&quot;,&quot;netmask&quot;:&quot;255.255.0.0&quot;}],
        ///&quot;ipv6&quot;:[{&quot;address&quot;:&quot;fe80::209:e5ff:fe00:123a&quot;,&quot;prefix&quot;:6 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string CorrectMessage {
            get {
                return ResourceManager.GetString("CorrectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {&quot;jsonrpc&quot;:&quot;2.0&quot;,&quot;method&quot;:&quot;announce&quot;,&quot;params&quot;:{&quot;apiVersion&quot;:&quot;1.0&quot;,
        ///&quot;device&quot;:{&quot;familyType&quot;:&quot;QuantumX&quot;,&quot;firmwareVersion&quot;:&quot;4.1.1.18610.1&quot;,&quot;hardwareId&quot;:&quot;MX410_R0&quot;,
        ///&quot;name&quot;:&quot;MX410 Matthias&quot;,&quot;type&quot;:&quot;MX410&quot;,&quot;uuid&quot;:&quot;0009E500123B&quot;},&quot;expiration&quot;:15,
        ///&quot;netSettings&quot;:{&quot;defaultGateway&quot;:{&quot;ipv4Address&quot;:&quot;172.19.169.254&quot;},
        ///&quot;interface&quot;:{&quot;configurationMethod&quot;:&quot;dhcp&quot;,&quot;description&quot;:&quot;ethernet backplane side&quot;,
        ///&quot;ipv4&quot;:[{&quot;address&quot;:&quot;172.19.192.57&quot;,&quot;netmask&quot;:&quot;255.255.0.0&quot;}],
        ///&quot;ipv6&quot;:[{&quot;address&quot;:&quot;fe80::209:e5ff:fe00:123a&quot;,&quot;prefix&quot;:6 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string CorrectMessage_UUID0009E500123B {
            get {
                return ResourceManager.GetString("CorrectMessage_UUID0009E500123B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {&quot;jsonrpc&quot;:&quot;2.0&quot;,&quot;method&quot;:&quot;announce&quot;,
        ///&quot;params&quot;:{&quot;apiVersion&quot;:&quot;1.0&quot;,&quot;device&quot;:{&quot;familyType&quot;:&quot;QuantumX&quot;,&quot;firmwareVersion&quot;:&quot;4.1.1.18610.1&quot;,
        ///&quot;hardwareId&quot;:&quot;MX410_R0&quot;,&quot;name&quot;:&quot;MX410 Matthias&quot;,&quot;type&quot;:&quot;MX410&quot;,&quot;uuid&quot;:&quot;0009E500123C&quot;},&quot;expiration&quot;:15,
        ///&quot;netSettings&quot;:{&quot;defaultGateway&quot;:{&quot;ipv4Address&quot;:&quot;172.19.169.254&quot;},
        ///&quot;interface&quot;:{&quot;description&quot;:&quot;ethernet backplane side&quot;,
        ///&quot;ipv4&quot;:[{&quot;address&quot;:&quot;172.19.192.57&quot;,&quot;netmask&quot;:&quot;255.255.0.0&quot;}],
        ///&quot;ipv6&quot;:[{&quot;address&quot;:&quot;fe80::209:e5ff:fe00:123a&quot;,&quot;prefix&quot;:64}],&quot;name&quot;:&quot;eth0&quot;,&quot;type&quot;:&quot;eth [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string CorrectMessageDifferentDevice {
            get {
                return ResourceManager.GetString("CorrectMessageDifferentDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {&quot;jsonrpc&quot;:&quot;2.0&quot;,&quot;method&quot;:&quot;announce&quot;,&quot;params&quot;:{&quot;apiVersion&quot;:&quot;1.0&quot;,
        ///&quot;device&quot;:{&quot;familyType&quot;:&quot;QuantumX&quot;,&quot;firmwareVersion&quot;:&quot;4.1.1.18610.1&quot;,&quot;hardwareId&quot;:&quot;MX410_R0&quot;,
        ///&quot;name&quot;:&quot;MX410 Matthias&quot;,&quot;type&quot;:&quot;MX410&quot;,&quot;uuid&quot;:&quot;0009E500123A&quot;},&quot;expiration&quot;:-15,
        ///&quot;netSettings&quot;:{&quot;defaultGateway&quot;:{&quot;ipv4Address&quot;:&quot;172.19.169.254&quot;},
        ///&quot;interface&quot;:{&quot;configurationMethod&quot;:&quot;dhcp&quot;,&quot;description&quot;:&quot;ethernet backplane side&quot;,
        ///&quot;ipv4&quot;:[{&quot;address&quot;:&quot;172.19.192.57&quot;,&quot;netmask&quot;:&quot;255.255.0.0&quot;}],
        ///&quot;ipv6&quot;:[{&quot;address&quot;:&quot;fe80::209:e5ff:fe00:123a&quot;,&quot;prefix&quot;: [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string CorrectMessageNegativeExpire {
            get {
                return ResourceManager.GetString("CorrectMessageNegativeExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {&quot;jsonrpc&quot;:&quot;2.0&quot;,&quot;method&quot;:&quot;announce&quot;,&quot;params&quot;:{&quot;apiVersion&quot;:&quot;1.0&quot;,
        ///&quot;device&quot;:{&quot;familyType&quot;:&quot;QuantumX&quot;,&quot;firmwareVersion&quot;:&quot;4.1.1.18610.1&quot;,&quot;hardwareId&quot;:&quot;MX410_R0&quot;,
        ///&quot;name&quot;:&quot;MX410 Matthias&quot;,&quot;type&quot;:&quot;MX410&quot;,&quot;uuid&quot;:&quot;0009E500123A&quot;},
        ///&quot;netSettings&quot;:{&quot;defaultGateway&quot;:{&quot;ipv4Address&quot;:&quot;172.19.169.254&quot;},
        ///&quot;interface&quot;:{&quot;configurationMethod&quot;:&quot;dhcp&quot;,&quot;description&quot;:&quot;ethernet backplane side&quot;,
        ///&quot;ipv4&quot;:[{&quot;address&quot;:&quot;172.19.192.57&quot;,&quot;netmask&quot;:&quot;255.255.0.0&quot;}],
        ///&quot;ipv6&quot;:[{&quot;address&quot;:&quot;fe80::209:e5ff:fe00:123a&quot;,&quot;prefix&quot;:64}],&quot;name&quot;:&quot;eth0 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string CorrectMessageNoExpire {
            get {
                return ResourceManager.GetString("CorrectMessageNoExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {&quot;jsonrpc&quot;:&quot;2.0&quot;,&quot;method&quot;:&quot;announce&quot;,&quot;params&quot;:{&quot;apiVersion&quot;:&quot;1.0&quot;,
        ///&quot;device&quot;:{&quot;familyType&quot;:&quot;QuantumX&quot;,&quot;firmwareVersion&quot;:&quot;4.1.1.18610.1&quot;,&quot;hardwareId&quot;:&quot;MX410_R0&quot;,
        ///&quot;name&quot;:&quot;MX410 Matthias&quot;,&quot;type&quot;:&quot;MX410&quot;,&quot;uuid&quot;:&quot;0009E500123A&quot;},&quot;expiration&quot;:1,
        ///&quot;netSettings&quot;:{&quot;defaultGateway&quot;:{&quot;ipv4Address&quot;:&quot;172.19.169.254&quot;},
        ///&quot;interface&quot;:{&quot;configurationMethod&quot;:&quot;dhcp&quot;,&quot;description&quot;:&quot;ethernet backplane side&quot;,
        ///&quot;ipv4&quot;:[{&quot;address&quot;:&quot;172.19.192.57&quot;,&quot;netmask&quot;:&quot;255.255.0.0&quot;}],
        ///&quot;ipv6&quot;:[{&quot;address&quot;:&quot;fe80::209:e5ff:fe00:123a&quot;,&quot;prefix&quot;:64 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string CorrectMessageNoServices {
            get {
                return ResourceManager.GetString("CorrectMessageNoServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {&quot;jsonrpc&quot;:&quot;2.0&quot;,&quot;method&quot;:&quot;announce&quot;,&quot;params&quot;:{&quot;apiVersion&quot;:&quot;1.0&quot;,
        ///&quot;device&quot;:{&quot;familyType&quot;:&quot;QuantumX&quot;,&quot;firmwareVersion&quot;:&quot;4.1.1.18610.1&quot;,&quot;hardwareId&quot;:&quot;MX410_R0&quot;,
        ///&quot;name&quot;:&quot;MX410 Matthias&quot;,&quot;type&quot;:&quot;MX410&quot;,&quot;uuid&quot;:&quot;0009E500123A&quot;},&quot;expiration&quot;:1,
        ///&quot;netSettings&quot;:{&quot;defaultGateway&quot;:{&quot;ipv4Address&quot;:&quot;172.19.169.254&quot;},
        ///&quot;interface&quot;:{&quot;configurationMethod&quot;:&quot;dhcp&quot;,&quot;description&quot;:&quot;ethernet backplane side&quot;,
        ///&quot;ipv4&quot;:[{&quot;address&quot;:&quot;172.19.192.57&quot;,&quot;netmask&quot;:&quot;255.255.0.0&quot;}],
        ///&quot;ipv6&quot;:[{&quot;address&quot;:&quot;fe80::209:e5ff:fe00:123a&quot;,&quot;prefix&quot;:64 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string CorrectMessageShortExpire {
            get {
                return ResourceManager.GetString("CorrectMessageShortExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {&quot;jsonrpc&quot;:&quot;2.0&quot;,&quot;method&quot;:&quot;announce&quot;,
        ///&quot;params&quot;:{&quot;apiVersion&quot;:&quot;1.0&quot;,&quot;device&quot;:{&quot;familyType&quot;:&quot;QuantumX&quot;,&quot;firmwareVersion&quot;:&quot;4.1.1.18610.1&quot;,
        ///&quot;hardwareId&quot;:&quot;MX410_R0&quot;,&quot;name&quot;:&quot;MX410 Matthias&quot;,&quot;type&quot;:&quot;MX410&quot;,&quot;uuid&quot;:&quot;0009E500123A&quot;},&quot;expiration&quot;:15,
        ///&quot;netSettings&quot;:{&quot;defaultGateway&quot;:{&quot;ipv4Address&quot;:&quot;172.19.169.254&quot;},
        ///&quot;interface&quot;:{&quot;description&quot;:&quot;ethernet backplane side&quot;,
        ///&quot;ipv4&quot;:[{&quot;address&quot;:&quot;172.19.192.57&quot;,&quot;netmask&quot;:&quot;255.255.0.0&quot;}],
        ///&quot;ipv6&quot;:[{&quot;address&quot;:&quot;fe80::209:e5ff:fe00:123a&quot;,&quot;prefix&quot;:64}],&quot;name&quot;:&quot;eth0&quot;,&quot;type&quot;:&quot;eth [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string CorretMessageDifferentServices {
            get {
                return ResourceManager.GetString("CorretMessageDifferentServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {&quot;jsonrpc&quot;:&quot;2.0&quot;,&quot;method&quot;:&quot;announce&quot;,
        ///&quot;params&quot;:{&quot;apiVersion&quot;:&quot;1.0&quot;,&quot;device&quot;:{&quot;familyType&quot;:&quot;QuantumX&quot;,&quot;firmwareVersion&quot;:&quot;4.1.1.18610.1&quot;,
        ///&quot;hardwareId&quot;:&quot;MX410_R0&quot;,&quot;name&quot;:&quot;MX410 Matthias&quot;,&quot;type&quot;:&quot;MX410&quot;,&quot;uuid&quot;:&quot;0009E500123A&quot;},&quot;expiration&quot;:1,
        ///&quot;netSettings&quot;:{&quot;defaultGateway&quot;:{&quot;ipv4Address&quot;:&quot;172.19.169.254&quot;},
        ///&quot;interface&quot;:{&quot;description&quot;:&quot;ethernet backplane side&quot;,
        ///&quot;ipv4&quot;:[{&quot;address&quot;:&quot;172.19.192.57&quot;,&quot;netmask&quot;:&quot;255.255.0.0&quot;}],
        ///&quot;ipv6&quot;:[{&quot;address&quot;:&quot;fe80::209:e5ff:fe00:123a&quot;,&quot;prefix&quot;:64}],&quot;name&quot;:&quot;eth0&quot;,&quot;type&quot;:&quot;ethe [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string CorretMessageDifferentServicesShortExpire {
            get {
                return ResourceManager.GetString("CorretMessageDifferentServicesShortExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {&quot;jsonrpc&quot;:&quot;2.0&quot;,&quot;method&quot;:&quot;announce&quot;,
        ///&quot;params&quot;:{&quot;apiVersion&quot;:&quot;1.0&quot;,&quot;device&quot;:{&quot;familyType&quot;:&quot;QuantumX&quot;,&quot;firmwareVersion&quot;:&quot;4.1.1.18610.1&quot;,\
        ///&quot;hardwareId&quot;:&quot;MX410_R0&quot;,&quot;name&quot;:&quot;MX410 Matthias&quot;,&quot;type&quot;:&quot;MX410&quot;,&quot;uuid&quot;:&quot;&quot;},&quot;expiration&quot;:15,
        ///&quot;netSettings&quot;:{&quot;defaultGateway&quot;:{&quot;ipv4Address&quot;:&quot;172.19.169.254&quot;},
        ///&quot;interface&quot;:{&quot;description&quot;:&quot;ethernet backplane side&quot;,
        ///&quot;ipv4&quot;:[{&quot;address&quot;:&quot;172.19.192.57&quot;,&quot;netmask&quot;:&quot;255.255.0.0&quot;}],
        ///&quot;ipv6&quot;:[{&quot;address&quot;:&quot;fe80::209:e5ff:fe00:123a&quot;,&quot;prefix&quot;:64}],&quot;name&quot;:&quot;eth0&quot;,&quot;type&quot;:&quot;ethernet&quot;}}}} ähnelt.
        /// </summary>
        internal static string EmptyDeviceUuidMessage {
            get {
                return ResourceManager.GetString("EmptyDeviceUuidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {&quot;jsonrpc&quot;:&quot;2.0&quot;,&quot;method&quot;:&quot;announce&quot;,
        ///&quot;params&quot;:{&quot;apiVersion&quot;:&quot;1.0&quot;,&quot;device&quot;:{&quot;familyType&quot;:&quot;QuantumX&quot;,&quot;firmwareVersion&quot;:&quot;4.1.1.18610.1&quot;,
        ///&quot;hardwareId&quot;:&quot;MX410_R0&quot;,&quot;name&quot;:&quot;MX410 Matthias&quot;,&quot;type&quot;:&quot;MX410&quot;,&quot;uuid&quot;:&quot;0009E500123A&quot;},&quot;expiration&quot;:15,
        ///&quot;netSettings&quot;:{&quot;defaultGateway&quot;:{&quot;ipv4Address&quot;:&quot;172.19.169.254&quot;},
        ///&quot;interface&quot;:{&quot;description&quot;:&quot;ethernet backplane side&quot;,
        ///&quot;ipv4&quot;:[{&quot;address&quot;:&quot;172.19.192.57&quot;,&quot;netmask&quot;:&quot;255.255.0.0&quot;}],
        ///&quot;ipv6&quot;:[{&quot;address&quot;:&quot;fe80::209:e5ff:fe00:123a&quot;,&quot;prefix&quot;:64}],&quot;name&quot;:&quot;&quot;,&quot;type&quot;:&quot;etherne [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string EmptyInterfaceNameMessage {
            get {
                return ResourceManager.GetString("EmptyInterfaceNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {&quot;jsonrpc&quot;:&quot;2.0&quot;,&quot;method&quot;:&quot;announce&quot;,
        ///&quot;params&quot;:{&quot;apiVersion&quot;:&quot;1.0&quot;,&quot;device&quot;:{&quot;familyType&quot;:&quot;QuantumX&quot;,&quot;firmwareVersion&quot;:&quot;4.1.1.18610.1&quot;,
        ///&quot;hardwareId&quot;:&quot;MX410_R0&quot;,&quot;name&quot;:&quot;MX410 Matthias&quot;,&quot;type&quot;:&quot;MX410&quot;,&quot;uuid&quot;:&quot;0009E500123A&quot;},&quot;expiration&quot;:15,
        ///&quot;netSettings&quot;:{&quot;defaultGateway&quot;:{&quot;ipv4Address&quot;:&quot;172.19.169.254&quot;},
        ///&quot;interface&quot;:{&quot;description&quot;:&quot;ethernet backplane side&quot;,
        ///&quot;ipv4&quot;:[{&quot;address&quot;:&quot;172.19.192.57&quot;,&quot;netmask&quot;:&quot;255.255.0.0&quot;}],
        ///&quot;ipv6&quot;:[{&quot;address&quot;:&quot;fe80::209:e5ff:fe00:123a&quot;,&quot;prefix&quot;:64}],
        ///&quot;name&quot;:&quot;eth0&quot;,&quot;type&quot;:&quot;e [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string EmptyRouterUuidMessage {
            get {
                return ResourceManager.GetString("EmptyRouterUuidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {&quot;jsonrpc&quot;:&quot;2.0&quot;,&quot;method&quot;:&quot;announce&quot;,
        ///&quot;params&quot;:&quot;apiVersion&quot;:&quot;1.0&quot;,&quot;device&quot;:{&quot;familyType&quot;:&quot;QuantumX&quot;,&quot;firmwareVersion&quot;:&quot;4.1.1.18610.1&quot;,
        ///&quot;hardwareId&quot;:&quot;MX410_R0&quot;,&quot;name&quot;:&quot;MX410 Matthias&quot;,&quot;type&quot;:&quot;MX410&quot;,&quot;uuid&quot;:&quot;0009E500123A&quot;},&quot;expiration&quot;:15,
        ///&quot;netSettings&quot;:{&quot;defaultGateway&quot;:{&quot;ipv4Address&quot;:&quot;172.19.169.254&quot;},
        ///&quot;interface&quot;:{&quot;description&quot;:&quot;ethernet backplane side&quot;,
        ///&quot;ipv4&quot;:[{&quot;address&quot;:&quot;172.19.192.57&quot;,&quot;netmask&quot;:&quot;255.255.0.0&quot;}],
        ///&quot;ipv6&quot;:[{&quot;address&quot;:&quot;fe80::209:e5ff:fe00:123a&quot;,&quot;prefix&quot;:64}],&quot;name&quot;:&quot;eth0&quot;,&quot;type&quot;:&quot;ethe [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string InvalidJsonMessage {
            get {
                return ResourceManager.GetString("InvalidJsonMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {&quot;jsonrpc&quot;:&quot;2.0&quot;,&quot;method&quot;:&quot;announce&quot;,
        ///&quot;params&quot;:{&quot;apiVersion&quot;:&quot;1.0&quot;,&quot;expiration&quot;:15,
        ///&quot;netSettings&quot;:{&quot;defaultGateway&quot;:{&quot;ipv4Address&quot;:&quot;172.19.169.254&quot;},
        ///&quot;interface&quot;:{&quot;description&quot;:&quot;ethernet backplane side&quot;,
        ///&quot;ipv4&quot;:[{&quot;address&quot;:&quot;172.19.192.57&quot;,&quot;netmask&quot;:&quot;255.255.0.0&quot;}],
        ///&quot;ipv6&quot;:[{&quot;address&quot;:&quot;fe80::209:e5ff:fe00:123a&quot;,&quot;prefix&quot;:64}],&quot;name&quot;:&quot;eth0&quot;,&quot;type&quot;:&quot;ethernet&quot;}}}} ähnelt.
        /// </summary>
        internal static string MissingDeviceMessage {
            get {
                return ResourceManager.GetString("MissingDeviceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {&quot;jsonrpc&quot;:&quot;2.0&quot;,&quot;method&quot;:&quot;announce&quot;,
        ///&quot;params&quot;:{&quot;apiVersion&quot;:&quot;1.0&quot;,&quot;device&quot;:{&quot;familyType&quot;:&quot;QuantumX&quot;,&quot;firmwareVersion&quot;:&quot;4.1.1.18610.1&quot;,
        ///&quot;hardwareId&quot;:&quot;MX410_R0&quot;,&quot;name&quot;:&quot;MX410 Matthias&quot;,&quot;type&quot;:&quot;MX410&quot;},&quot;expiration&quot;:15,
        ///&quot;netSettings&quot;:{&quot;defaultGateway&quot;:{&quot;ipv4Address&quot;:&quot;172.19.169.254&quot;},
        ///&quot;interface&quot;:{&quot;description&quot;:&quot;ethernet backplane side&quot;,
        ///&quot;ipv4&quot;:[{&quot;address&quot;:&quot;172.19.192.57&quot;,&quot;netmask&quot;:&quot;255.255.0.0&quot;}],
        ///&quot;ipv6&quot;:[{&quot;address&quot;:&quot;fe80::209:e5ff:fe00:123a&quot;,&quot;prefix&quot;:64}],&quot;name&quot;:&quot;eth0&quot;,&quot;type&quot;:&quot;ethernet&quot;}}}} ähnelt.
        /// </summary>
        internal static string MissingDeviceUuidMessage {
            get {
                return ResourceManager.GetString("MissingDeviceUuidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {&quot;jsonrpc&quot;:&quot;2.0&quot;,&quot;method&quot;:&quot;announce&quot;,
        ///&quot;params&quot;:{&quot;apiVersion&quot;:&quot;1.0&quot;,&quot;device&quot;:{&quot;firmwareVersion&quot;:&quot;4.1.1.18610.1&quot;,&quot;hardwareId&quot;:&quot;MX410_R0&quot;,
        ///&quot;name&quot;:&quot;MX410 Matthias&quot;,&quot;type&quot;:&quot;MX410&quot;,&quot;uuid&quot;:&quot;0009E500123A&quot;},&quot;expiration&quot;:15,
        ///&quot;netSettings&quot;:{&quot;defaultGateway&quot;:{&quot;ipv4Address&quot;:&quot;172.19.169.254&quot;},
        ///&quot;interface&quot;:{&quot;description&quot;:&quot;ethernet backplane side&quot;,
        ///&quot;ipv4&quot;:[{&quot;address&quot;:&quot;172.19.192.57&quot;,&quot;netmask&quot;:&quot;255.255.0.0&quot;}],
        ///&quot;ipv6&quot;:[{&quot;address&quot;:&quot;fe80::209:e5ff:fe00:123a&quot;,&quot;prefix&quot;:64}],&quot;name&quot;:&quot;eth0&quot;,&quot;type&quot;:&quot;ethernet&quot;}}}} ähnelt.
        /// </summary>
        internal static string MissingFamilytypeMessage {
            get {
                return ResourceManager.GetString("MissingFamilytypeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {&quot;id&quot;:&quot;TEST-UUID&quot;,&quot;jsonrpc&quot;:&quot;2.0&quot;} ähnelt.
        /// </summary>
        internal static string MissingMethodMessage {
            get {
                return ResourceManager.GetString("MissingMethodMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {&quot;jsonrpc&quot;:&quot;2.0&quot;,&quot;method&quot;:&quot;announce&quot;} ähnelt.
        /// </summary>
        internal static string MissingParamsMessage {
            get {
                return ResourceManager.GetString("MissingParamsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {&quot;jsonrpc&quot;:&quot;2.0&quot;,&quot;method&quot;:&quot;announce&quot;,
        ///&quot;params&quot;:{&quot;apiVersion&quot;:&quot;1.0&quot;,&quot;device&quot;:{&quot;familyType&quot;:&quot;QuantumX&quot;,&quot;firmwareVersion&quot;:&quot;4.1.1.18610.1&quot;,
        ///&quot;hardwareId&quot;:&quot;MX410_R0&quot;,&quot;name&quot;:&quot;MX410 Matthias&quot;,&quot;type&quot;:&quot;MX410&quot;,&quot;uuid&quot;:&quot;0009E500123A&quot;},
        ///&quot;expiration&quot;:15,&quot;netSettings&quot;:{&quot;defaultGateway&quot;:{&quot;ipv4Address&quot;:&quot;172.19.169.254&quot;},
        ///&quot;interface&quot;:{&quot;description&quot;:&quot;ethernet backplane side&quot;,
        ///&quot;ipv4&quot;:[{&quot;address&quot;:&quot;172.19.192.57&quot;,&quot;netmask&quot;:&quot;255.255.0.0&quot;}],
        ///&quot;ipv6&quot;:[{&quot;address&quot;:&quot;fe80::209:e5ff:fe00:123a&quot;,&quot;prefix&quot;:64}],
        ///&quot;name&quot;:&quot;eth0&quot;,&quot;type&quot;:&quot;e [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string MissingRouterUuidMessage {
            get {
                return ResourceManager.GetString("MissingRouterUuidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {&quot;jsonrpc&quot;:&quot;2.0&quot;,&quot;method&quot;:&quot;announce&quot;,
        ///&quot;params&quot;:{&quot;apiVersion&quot;:&quot;1.0&quot;,&quot;device&quot;:{&quot;familyType&quot;:&quot;QuantumX&quot;,
        ///&quot;firmwareVersion&quot;:&quot;4.1.1.18610.1&quot;,&quot;hardwareId&quot;:&quot;MX410_R0&quot;,&quot;name&quot;:&quot;MX410 Matthias&quot;,
        ///&quot;type&quot;:&quot;MX410&quot;,&quot;uuid&quot;:&quot;0009E500123A&quot;},&quot;expiration&quot;:15,
        ///&quot;netSettings&quot;:{&quot;defaultGateway&quot;:{&quot;ipv4Address&quot;:&quot;172.19.169.254&quot;}}}} ähnelt.
        /// </summary>
        internal static string NoInterfaceMessage {
            get {
                return ResourceManager.GetString("NoInterfaceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {&quot;jsonrpc&quot;:&quot;2.0&quot;,&quot;method&quot;:&quot;announce&quot;,
        ///&quot;params&quot;:{&quot;apiVersion&quot;:&quot;1.0&quot;,&quot;device&quot;:{&quot;familyType&quot;:&quot;QuantumX&quot;,
        ///&quot;firmwareVersion&quot;:&quot;4.1.1.18610.1&quot;,&quot;hardwareId&quot;:&quot;MX410_R0&quot;,&quot;name&quot;:&quot;MX410 Matthias&quot;,
        ///&quot;type&quot;:&quot;MX410&quot;,&quot;uuid&quot;:&quot;0009E500123A&quot;},&quot;expiration&quot;:15,
        ///&quot;netSettings&quot;:{&quot;defaultGateway&quot;:{&quot;ipv4Address&quot;:&quot;172.19.169.254&quot;},
        ///&quot;interface&quot;:{&quot;description&quot;:&quot;ethernet backplane side&quot;,
        ///&quot;ipv4&quot;:[{&quot;address&quot;:&quot;172.19.192.57&quot;,&quot;netmask&quot;:&quot;255.255.0.0&quot;}],
        ///&quot;ipv6&quot;:[{&quot;address&quot;:&quot;fe80::209:e5ff:fe00:123a&quot;,&quot;prefix&quot;:64}],&quot;type&quot;:&quot;ethernet&quot;}}}} ähnelt.
        /// </summary>
        internal static string NoInterfaceNameMessage {
            get {
                return ResourceManager.GetString("NoInterfaceNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [] ähnelt.
        /// </summary>
        internal static string NoJsonRpc {
            get {
                return ResourceManager.GetString("NoJsonRpc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {&quot;jsonrpc&quot;:&quot;2.0&quot;,&quot;method&quot;:&quot;announce&quot;,
        ///&quot;params&quot;:{&quot;apiVersion&quot;:&quot;1.0&quot;,&quot;device&quot;:{&quot;familyType&quot;:&quot;QuantumX&quot;,&quot;firmwareVersion&quot;:&quot;4.1.1.18610.1&quot;,
        ///&quot;hardwareId&quot;:&quot;MX410_R0&quot;,&quot;name&quot;:&quot;MX410 Matthias&quot;,&quot;type&quot;:&quot;MX410&quot;,&quot;uuid&quot;:&quot;0009E500123A&quot;},&quot;expiration&quot;:15}} ähnelt.
        /// </summary>
        internal static string NoNetSettingsMessage {
            get {
                return ResourceManager.GetString("NoNetSettingsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {&quot;method&quot;:&quot;blah&quot;,&quot;jsonrpc&quot;:&quot;2.0&quot;} ähnelt.
        /// </summary>
        internal static string NotAnnounceMessage {
            get {
                return ResourceManager.GetString("NotAnnounceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {&quot;jsonrpc&quot;:&quot;2.0&quot;,&quot;method&quot;:&quot;announce&quot;,&quot;params&quot;:{
        ///&quot;device&quot;:{&quot;familyType&quot;:&quot;QuantumX&quot;,&quot;firmwareVersion&quot;:&quot;4.1.1.18610.1&quot;,&quot;hardwareId&quot;:&quot;MX410_R0&quot;,
        ///&quot;name&quot;:&quot;MX410 Matthias&quot;,&quot;type&quot;:&quot;MX410&quot;,&quot;uuid&quot;:&quot;0009E500123A&quot;},&quot;expiration&quot;:15,
        ///&quot;netSettings&quot;:{&quot;defaultGateway&quot;:{&quot;ipv4Address&quot;:&quot;172.19.169.254&quot;},
        ///&quot;interface&quot;:{&quot;configurationMethod&quot;:&quot;dhcp&quot;,&quot;description&quot;:&quot;ethernet backplane side&quot;,
        ///&quot;ipv4&quot;:[{&quot;address&quot;:&quot;172.19.192.57&quot;,&quot;netmask&quot;:&quot;255.255.0.0&quot;}],
        ///&quot;ipv6&quot;:[{&quot;address&quot;:&quot;fe80::209:e5ff:fe00:123a&quot;,&quot;prefix&quot;:64}],&quot;name&quot;:&quot;eth0&quot;,&quot; [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string NoVersionMessage {
            get {
                return ResourceManager.GetString("NoVersionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {&quot;jsonrpc&quot;:&quot;2.0&quot;,&quot;method&quot;:&quot;announce&quot;,&quot;params&quot;:{&quot;apiVersion&quot;:&quot;1.1&quot;,
        ///&quot;device&quot;:{&quot;familyType&quot;:&quot;QuantumX&quot;,&quot;firmwareVersion&quot;:&quot;4.1.1.18610.1&quot;,&quot;hardwareId&quot;:&quot;MX410_R0&quot;,
        ///&quot;name&quot;:&quot;MX410 Matthias&quot;,&quot;type&quot;:&quot;MX410&quot;,&quot;uuid&quot;:&quot;0009E500123A&quot;},&quot;expiration&quot;:15,
        ///&quot;netSettings&quot;:{&quot;defaultGateway&quot;:{&quot;ipv4Address&quot;:&quot;172.19.169.254&quot;},
        ///&quot;interface&quot;:{&quot;configurationMethod&quot;:&quot;dhcp&quot;,&quot;description&quot;:&quot;ethernet backplane side&quot;,
        ///&quot;ipv4&quot;:[{&quot;address&quot;:&quot;172.19.192.57&quot;,&quot;netmask&quot;:&quot;255.255.0.0&quot;}],
        ///&quot;ipv6&quot;:[{&quot;address&quot;:&quot;fe80::209:e5ff:fe00:123a&quot;,&quot;prefix&quot;:6 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string WrongVersionMessage {
            get {
                return ResourceManager.GetString("WrongVersionMessage", resourceCulture);
            }
        }
    }
}
